In [7]:
"""
Read in anonymized data, output features matrix for modeling
"""
import pandas as pd
import re

# read in data
df = pd.read_csv('../data/CYSOanonymized.csv')

# set financial aid status to 0 if NaN

df['finaid'].fillna(0,inplace=True)

# parse race into different rows
df['race'].fillna('Other',inplace=True)
df['caucasian']=0
df['african_american']=0
df['native_american']=0
df['latino']=0
df['asian']=0
df['other_race']=0
df['race_num']=0

for index, row in df.iterrows():
    if re.search('cauc', str(row['race']), re.IGNORECASE):
        df.loc[index,'caucasian']=1
        df.loc[index,'race_num']=df.loc[index,'race_num']+1
    if re.search('african', str(row['race']), re.IGNORECASE):
        df.loc[index,'african_american']=1
        df.loc[index,'race_num']=df.loc[index,'race_num']+1
    if re.search('native', str(row['race']), re.IGNORECASE):
        df.loc[index,'native_american']=1
        df.loc[index,'race_num']=df.loc[index,'race_num']+1
    if re.search('latino', str(row['race']), re.IGNORECASE):
        df.loc[index,'latino']=1
        df.loc[index,'race_num']=df.loc[index,'race_num']+1
    if re.search('asian', str(row['race']), re.IGNORECASE):
        if not re.search('caucasian', str(row['race']), re.IGNORECASE):
            df.loc[index,'asian']=1
            df.loc[index,'race_num']=df.loc[index,'race_num']+1
    if re.search('other', str(row['race']), re.IGNORECASE):
        df.loc[index,'other_race']=1
        df.loc[index,'race_num']=df.loc[index,'race_num']+1
    if re.search("`", str(row['race']), re.IGNORECASE):
        df.loc[index,'other_race']=1
        df.loc[index,'race_num']=df.loc[index,'race_num']+1

# compile gender
df['male']=0
df['female']=0

df.gender = df.gender.str.strip()
df.gender.replace('Male','M',inplace=True)
df.gender.replace('Female','F',inplace=True)

for index, row in df.iterrows():
    if row['gender']=='M':
        df.loc[index, 'male']=1
    if row['gender']=='F':
        df.loc[index,'female']=1

# compile major

df['music']=0

music_terms = ['performance','music','violin','songwriting','perfomance','bass','cello','viola','jazz']

for index, row in df.iterrows():
    for music_term in music_terms:
        if re.search(music_term,str(row['major']),re.IGNORECASE):
            df.loc[index,'music']=1
    

'''
map in and combine incomes
'''
#read in incomes and convert to numeric
income = pd.read_csv('../data/income_zip.csv')
df['homezip']=pd.to_numeric(df['homezip'], errors='coerce')

# merge with data structure
df = pd.merge(df,income,how='left',left_on='homezip',right_on='Zip')


# rename and reformat columns
df.rename(index=str, columns={"Mean": "mean_income", "Median": "median_income", \
                              "finaid" : "financial_aid", "race_num" : "multiracial"}, inplace=True)
df['mean_income'] = df['median_income'].str.replace(',','')
df['mean_income']=pd.to_numeric(df['mean_income'], errors='coerce')
df['median_income'] = df['median_income'].str.replace(',','')
df['median_income']=pd.to_numeric(df['median_income'], errors='coerce')
df['income_diff']=df['mean_income']-df['median_income']

'''
map in and combine college data
'''

# read in college data
uf = pd.read_csv('../data/colleges.csv')

uf = uf[['displayName','acceptance-rate','institutionalControl']]



# save full data structure
df.to_csv('../data/exploring_data.csv')

# merge into data frame


# # drop all data not used in modeling - comment in when prepping data
# df.drop(['Zip', 'Pop', 'Unnamed: 0','instrument','race','gender','s_ensemble',\
#         'm_employ','m_job','d_employ','school','s_address','uni','pt',\
#         's_state','major','homezip','s_zip','studentID','mean_income',
#         'gradyear','female','native_american','income_diff'], axis=1, inplace=True)



# save fitting data structure
df.to_csv('../data/fitting_data.csv')

In [8]:
uf

,displayName,acceptance-rate,institutionalControl
0,Princeton University,7,private
1,Harvard University,5,private
2,University of Chicago,8,private
3,Yale University,6,private
4,Columbia University,6,private
5,Massachusetts Institute of Technology,8,private
6,Stanford University,5,private
7,University of Pennsylvania,9,private
8,Duke University,11,private
9,California Institute of Technology,8,private
10,Dartmouth College,11,private
11,Johns Hopkins University,12,private
12,Northwestern University,11,private
13,Brown University,9,private
14,Cornell University,14,private
15,Rice University,15,private
16,Vanderbilt University,11,private
17,University of Notre Dame,19,private
18,Washington University in St. Louis,17,private
19,Georgetown University,17,private
20,Emory University,25,private
21,University of California--Berkeley,16,public
22,University of California--Los Angeles,18,public
23,University of Southern California,17,private
24,Carnegie Mellon University,22,private
25,University of Virginia,30,public
26,Wake Forest University,30,private
27,University of Michigan--Ann Arbor,29,public
28,Tufts University,14,private
29,New York University,32,private
...,...,...,...
332,Olin College of Engineering,11,private
333,Bowdoin College,14,private
334,St. Olaf College,36,private
335,none,none,none
336,La Haute Ecole de Musique de Lausanne,10,public
337,College of the Holy Cross,37,private
338,Boston Conservatory,46,private
339,Chicago College of Performing Arts,70,private
340,Wheaton College,70,private
341,Colorado College,17.1,private
342,Luther College,67,private
343,Mannes School of Music,24,private
344,Seminole State College Altamonte Springs,100,public
345,San Francisco Conservatory,47,private
346,Conservatory of Paris,3,private
347,North Central College,57,private
348,OberlinConservatoryofMusic,29,private
349,UniversityofBritishColumbia,52,public
350,WesternIllinois,60,public
351,UniversityofWisconsinWhitewater,80,public
352,IllinoisWesleyanUniversity,62,private
353,HaroldWashingtonCollege,100,public
354,CreightonUniversity,71,private
355,ArtInstituteofCalifornia,51,private
356,BelmontUniversity,80,private
357,TheOhioStateUniversity,50,public
358,StetsonUniversity,64,private
359,CarrollUniversity,94,private
360,MountHolyokeCollege,50,private
361,HighPointUniversity,73,private

In [2]:
df.columns

Index(['financial_aid', 'caucasian', 'african_american', 'latino', 'asian',
       'other_race', 'multiracial', 'male', 'music', 'median_income'],
      dtype='object')